### ISSUE TITLE
[Mibench] Conflicting option -c 

### ISSUE THREAD

**Issue by reSHARMA** [hiraditya/Toolchains#16]
Our script uses -c option for picking up the toolchain container which conflicts with gcc. -c can be probably changed to -cc in riscv-compiler.py

**Comment by aryaanlambe** [comment]
Hello!
Can this issue be assigned to me? Are there any deadlines? 
:smile:

**Comment by reSHARMA** [comment]
@aryaanlambe glad to see you here! I'm really sorry I just came here to close this after merging the pr. If you are interested you can help us with #20
