### ISSUE TITLE
Support compilation of .o files

### ISSUE THREAD

**Issue by reSHARMA** [hiraditya/Toolchains#20]
As of now .c and .cpp files are compiled with riscv-cc and riscv-cxx respectively, it will be good if we could set riscv-cc for .o files as well.

This is handled in selectCompiler function here:
https://github.com/hiraditya/Toolchains/blob/master/riscv-compiler.py#L74

**Comment by aryaanlambe** [comment]
Can I be assigned this issue?
By when do you expect it done? :smile:

**Comment by aryaanlambe** [comment]
When do you expect results?

**Comment by reSHARMA** [comment]
It should not take longer, it's fine; take your time. We can wait for this for a week maybe. If you need any help, please don't hesitate :)

**Comment by aryaanlambe** [comment]
Awesome! I'll let you know if I hit any snags! :smile:

**Comment by aryaanlambe** [comment]
Not sure if this is all that is required, but this is the change I've made so far:
```
def selectCompiler(extention):
    compiler = ""
    if extention == "c":
            compiler = "riscv-cc"
    elif extention == "o":
            compiler = "riscv-cc"
    elif extention == "cpp":
            compiler = "riscv-cxx"
    return compiler
```

**Comment by reSHARMA** [comment]
Awesome! Looks good to me :) Can you please send a pull request?

**Comment by aryaanlambe** [comment]
Sure, I'll send it once I get home from Uni :smile:

**Comment by reSHARMA** [comment]
Any update, please don't hesitate to ask any question!

**Comment by aryaanlambe** [comment]
Hello, Sorry for the late reply :sweat_smile: 
I've created a pull request, please review it :smile:

**Comment by reSHARMA** [comment]
Ah, no worries :)

**Comment by reSHARMA** [comment]
Many thanks! Your patch supported few more benchmarks (https://github.com/hiraditya/Toolchains/commit/877e53b321f77881ac63d53ca3c4bae4041de6fb) :)
